version: "3"
services:
  socioregisterdb:
    image: postgres:latest
    container_name: socioregisterdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=socio_db
    restart: unless-stopped
# APP*****************************************
  socioregister:
    image: socioregister:latest
    container_name: socioregister
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - socioregisterdb
    links:
      - socioregisterdb
volumes:
  postgres-data:j
  
  
  
